-- migration: create meals table
-- purpose: central table for consumed meals with AI-calculated macros
-- relationship: 1:N with users (one user has many meals)
-- affected tables: meals

-- create meals table for tracking consumed food
create table public.meals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  consumed_at timestamptz not null,
  calories integer not null,
  protein numeric(10, 1) not null,
  fat numeric(10, 1) not null,
  carbs numeric(10, 1) not null,
  fiber numeric(10, 1) default 0,
  original_prompt text,
  last_ai_context jsonb,
  ai_suggestion text,
  is_image_analyzed boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- constraints: all macros and calories must be non-negative
  constraint macros_check check (
    calories >= 0 and
    protein >= 0 and
    fat >= 0 and
    carbs >= 0 and
    fiber >= 0
  )
);

comment on table public.meals is 'Consumed meals with AI-calculated nutritional values and interaction context';
comment on column public.meals.name is 'Meal name generated by AI (e.g. "Scrambled eggs with avocado")';
comment on column public.meals.consumed_at is 'Meal consumption time (UTC)';
comment on column public.meals.calories is 'Meal calories in kcal';
comment on column public.meals.protein is 'Protein in grams';
comment on column public.meals.fat is 'Fat in grams';
comment on column public.meals.carbs is 'Carbohydrates in grams';
comment on column public.meals.fiber is 'Fiber in grams';
comment on column public.meals.original_prompt is 'Original text entered by user';
comment on column public.meals.last_ai_context is 'AI conversation context dump (enables editing/correction)';
comment on column public.meals.ai_suggestion is 'Passive dietary suggestion from AI';
comment on column public.meals.is_image_analyzed is 'Flag indicating if meal was analyzed from a photo';

-- create trigger for automatic updated_at timestamp
create trigger meals_updated_at
  before update on public.meals
  for each row
  execute function public.handle_updated_at();

-- note: rls disabled for development - will be enabled in production

